# Day 1 - Data wrangling with Python - Exercises

## Exercise 1

#### Question 1
##### Assign variable `x` as your age and variable `y` as your neighbor's age.
##### Print `x` and `y`. 
##### Now swap `x` and `y` and print the result.

#### Answer:

In [12]:
import pandas as pd

a=pd.DataFrame({"x":range(5)}) * 2


b=pd.read_json('https://covidtracking.com/api/v1/states/daily.json')
b

,date,state,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,posNeg,deathIncrease,hospitalizedIncrease,hash,commercialScore,negativeRegularScore,negativeScore,positiveScore,score,grade
0,20200720,AK,2414.0,173172.0,NaN,29.0,NaN,NaN,NaN,0.0,...,175586,0,0,982ac1a1537b9b7a5d2dd768e419cece11dfe669,0,0,0,0,0,
1,20200720,AL,68891.0,524897.0,NaN,1563.0,8368.0,NaN,994.0,NaN,...,593788,4,586,78b0f0cdb400a84b5052f80e597bc11138f5848d,0,0,0,0,0,
2,20200720,AR,33927.0,398889.0,NaN,471.0,2202.0,NaN,NaN,111.0,...,432816,0,25,3bb85a05440526c23d60b70ad3388d236332589c,0,0,0,0,0,
3,20200720,AS,0.0,1037.0,NaN,NaN,NaN,NaN,NaN,NaN,...,1037,0,0,eb1949a094a8c4c95f33a9c6db8d407e917f5bdb,0,0,0,0,0,
4,20200720,AZ,145183.0,648340.0,NaN,3084.0,6698.0,886.0,NaN,622.0,...,793523,23,66,181888e74b302a4e4e3e90a0771e139657f9f0fe,0,0,0,0,0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7684,20200126,WA,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,0,0,7acb526e14f20a29cc74a0b32a37328bc6eac6c2,0,0,0,0,0,
7685,20200125,WA,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,0,0,9b52ca94dd2a996822542ea5f17a7363e7ad91cf,0,0,0,0,0,
7686,20200124,WA,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,0,0,094154f68e74bfc30b977cdee888f9c07be4360e,0,0,0,0,0,
7687,20200123,WA,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,0,0,e16af2a6a8f060355ff5ba499a28309a262c0b1e,0,0,0,0,0,
7688,20200122,WA,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,0,0,8f8db794931706272489cddd51e917a4a69c8c9b,0,0,0,0,0,

#### Question 2
##### Create a variable `numbers` with values 12345 as a string
##### Print the first and last elements in `numbers`
##### Print the length of the `numbers`.
##### Convert the type of `numbers` to integer
##### Print the type to verify your answer

#### Answer:

In [ ]:
ab = pd.read_csv("https://covidtracking.com/api/v1/states/daily.csv")

print(ab)

df = pd.read_json("https://covidtracking.com/api/v1/states/daily.json")

print(df)

#### Question 3
##### Create a `PrintHello` function so that it takes a name of a person as an argument and prints "Hello, [name]!".
##### Call the function to test whether it is working properly. Try out a few different names. 

#### Answer:

#### Question 4
##### Modify the function from Question 2 and name it `GetHelloMessage` so that it returns the message to be printed, but doesn't print it.
##### Call the function, assign its output to a variable `output_message` and then print the `output_message`.

#### Answer:

#### Question 5
##### Create a function called `find_range()` that takes a parameter `x`.
##### Return two numbers `x-10` and `x+10`.
##### Call the function by passing 25 to the function.

#### Answer:

#### Question 6
##### Create a function named `find_sum` that takes two parameters `a` and `b` and returns their sum.
##### Let `a` have a default value equal to 3 and `b` have a default value equal to 2.
##### Call the function without providing any arguments. What value do you get as a result?
##### Call the function by giving it the 2 arguments: 7 and 10.
##### Call the function providing a single argument 9 to the function. What value do you get in return?

#### Answer:

#### Question 7
##### Create an anonymous function that returns a reversed string and assign it to `palindrome` variable.
##### Call the function and use "No lemon, no melon" as the input and print the result.

#### Answer:

#### Question 8
##### Create a function called `factorial` which returns the factorial value of the given number `x`.
##### Call the function to print the factorial of 5, try a few other values.
##### _Hint: 4 factorial (4!) = 4 x 3 x 2 x 1 = 24._

#### Answer: